<?xml version="1.0" ?><root>
<report><version>2</version><sessionid>6fae88db7b6083b15fa8849a</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2020-11-08 19:06:13</createtime><buildsignature>Local.Unknown.Unknown.1.66.139.1020-1.200.000.464.Release</buildsignature><categoryid>career_rabbit_hole.py:62</categoryid><desyncid>6fae88db7b6083b15fa8849a</desyncid><systemconfig/><screenshot/><desyncdata>Exception during SI.cancel  running si_Career_Business:45 on None, cancel_reason_msg is SI State incompatible with new posture. Must cancel previous owning interaction for standExclusive:85: (AttributeError: 'NoneType' object has no attribute 'go_home_to_work_affordance')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 209, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 475, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 112, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 212, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 376, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\postures\posture_primitive.py", line 100, in posture_change&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 1066, in notify_posture_change_and_remove_incompatible_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 4825, in cancel&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 4592, in _cancel_eventually&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 4746, in _cancel&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 158, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 679, in &lt;lambda&gt;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 654, in _on_cancel&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\rabbit_hole\career_rabbit_hole.py", line 66, in select_travel_affordance&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\rabbit_hole\career_rabbit_hole.py", line 62, in get_travel_affordance&#13;&#10;AttributeError: 'NoneType' object has no attribute 'go_home_to_work_affordance'rtim=0&#13;&#10;Client Session Time: 21.02&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;Origin Version: 10,5,8,17910&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.18363 GPU: AMD Radeon R7 200 Series aticfx64.dll 26.20.12028.2, GUID: D7B71EE2-2B7D-11CF-F974-E8ECBBC2D735&#13; &#10;</desyncdata></report>
</root>